ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Controllers/ActividadFinancieraController.cs
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadFinanciera.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadFinanciera.Listar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadFinanciera.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadFinanciera.Registrar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.Actualizar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.General;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.General.Conversiones.ActividadFinanciera;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.BitacoraEventos;
using ControlDeRiesgoFinanciero.LN.ActividadFinanciera.Editar;
using ControlDeRiesgoFinanciero.LN.ActividadFinanciera.Listar;
using ControlDeRiesgoFinanciero.LN.ActividadFinanciera.ObtenerPorId;
using ControlDeRiesgoFinanciero.LN.ActividadFinanciera.Registrar;
using ControlDeRiesgoFinanciero.LN.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.LN.General;
using ControlDeRiesgoFinanciero.LN.General.Conversiones.ActividadFinanciera;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControlDeRiesgoFinanciero.UI.Controllers
{
    public class ActividadFinancieraController : Controller
    {
        IListarActividadFinancieraLN _listarActividadFinanciera;
        IRegistrarActividadFinancieraLN _registarActividades;
        IObtenerActividadFinancieraPorIdLN _obtenerPorId;
        IEditarActividadFinancieraLN _editarActividadN;
        ICambiarEstadoLN _cambiarEstado;
        IFecha _fecha;
        IRegistrarBitacoraEventosLN _registrarBitacora;

        public ActividadFinancieraController()
        {
            _listarActividadFinanciera = new ListarActividadFinancieraLN();
            _fecha = new Fecha();
            _registarActividades = new RegistrarActividadFinancieraLN();
            _editarActividadN = new EditarActividadFinancieraLN();
            _obtenerPorId = new ObtenerActividadFinancieraPorIdLN();
            _cambiarEstado = new CambiarEstadoLN(_fecha);
            _registrarBitacora = new RegistrarBitacoraEventosLN();

        }

        [Authorize(Roles = "Administrador")]
        // GET: ActividadFinanciera
        public ActionResult Index()
        {
            ViewBag.Title = "Las Actividades Financieras";
            List<ActividadFinancieraDto> laListaDeActividad = _listarActividadFinanciera.Listar();
            return View(laListaDeActividad);
        }

        [Authorize(Roles = "Administrador")]
        // GET: ActividadFinanciera/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]
        // GET: ActividadFinanciera/Create
        public ActionResult Create()
        {
       
            var modeloDeActividad = new ActividadFinancieraDto
            {
                Estado = true 
            };
            return View(modeloDeActividad);
        }

        [Authorize(Roles = "Administrador")]
        // POST: ActividadFinanciera/Create
        [HttpPost]
        public async Task<ActionResult> Create(ActividadFinancieraDto modeloDeActividad)
        {
            try
            {
                var existeActividad = _listarActividadFinanciera.Listar();
                bool actividadDuplicada = existeActividad
                    .Any(laActividad => laActividad.NombreActividadFinanciera == modeloDeActividad.NombreActividadFinanciera);

                if (!actividadDuplicada)
                {
                 
                    int cantidadDeDatosGuardados = await _registarActividades.Guardar(modeloDeActividad);

                   
                    await _registrarBitacora.Registrar(new BitacoraEventosDto
                    {
                        TablaDeEvento = "ACTIVIDAD_FINANCIERA",
                        TipoDeEvento = "Registrar",
                        FechaDeEvento = DateTime.Now,
                        DescripcionDeEvento = "Se registro una nueva actividad financiera",
                        DatosAnteriores = "Vacio",
                        DatosPosteriores = $"Nombre: {modeloDeActividad.NombreActividadFinanciera}",
                        StackTrace = ""
                    });
                    TempData["Alerta"] = "La actividad se registro correctamente.";
                    TempData.Keep("Alerta");
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Alerta"] = "Error al reactivar la actividad. Intente nuevamente.";
                    TempData.Keep("Alerta");
                    ModelState.AddModelError("NombreActividadFinanciera", "Ya existe una actividad con este nombre.");
               
                    return View(modeloDeActividad);
                }

            }
            catch (Exception ex)
            {
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "ACTIVIDAD_FINANCIERA",
                    TipoDeEvento = "Error",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Error al registrar una nueva actividad financiera",
                    DatosAnteriores = "", 
                    DatosPosteriores = "",
                    StackTrace = ex.StackTrace 
                });

                return View(modeloDeActividad);
            }
        }


        [Authorize(Roles = "Administrador")]
        // GET: ActividadFinanciera/Edit/5
        public ActionResult Edit(int id)
        {
            ActividadFinancieraDto laActividad = _obtenerPorId.Obtener(id);
            return View(laActividad);
        }

        [Authorize(Roles = "Administrador")]
        // POST: ActividadFinanciera/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(ActividadFinancieraDto laActividad)
        {
            try
            {
                var existeActividad = _listarActividadFinanciera.Listar();
                bool actividadDuplicada = existeActividad
                    .Any(laActividadValidada => laActividadValidada.NombreActividadFinanciera == laActividad.NombreActividadFinanciera && laActividadValidada.IdActividadFinanciera != laActividad.IdActividadFinanciera);

                if (actividadDuplicada)
                {
                    ModelState.AddModelError("NombreActividadFinanciera", "Ya existe una actividad con este nombre.");
                    return View(laActividad);
                }
                else
                {
                   
                    var actividadAnterior = _listarActividadFinanciera.Listar().FirstOrDefault(a => a.IdActividadFinanciera == laActividad.IdActividadFinanciera);

                    if (actividadAnterior != null)
                    {
                       
                      
                        await _registrarBitacora.Registrar(new BitacoraEventosDto
                        {
                            TablaDeEvento = "ACTIVIDAD_FINANCIERA",
                            TipoDeEvento = "Editar",
                            FechaDeEvento = DateTime.Now,
                            DescripcionDeEvento = $"Se actualizó la actividad financiera para la persona",
                            DatosAnteriores = $"Nombre: {actividadAnterior.NombreActividadFinanciera}\n" +
                            $"Descripción: {actividadAnterior.DescripcionActividadFinanciera}\n" +
                            $"Estado: {actividadAnterior.Estado}",
                            DatosPosteriores = $"Nombre: {laActividad.NombreActividadFinanciera}\n" +
                            $"Descripción: {laActividad.DescripcionActividadFinanciera}\n" +
                            $"Estado: {laActividad.Estado}",
                            StackTrace = "" 
                        });
                    }

                  
                    int cantidadDeDatosActualizados = await _editarActividadN.Actualizar(laActividad);

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
               
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "ACTIVIDAD_FINANCIERA",
                    TipoDeEvento = "Error",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Error al editar la actividad financiera",
                    DatosAnteriores = "", 
                    DatosPosteriores = "", 
                    StackTrace = ex.StackTrace
                });

                
                ViewBag.cantidadDeDatosActualizados = 0;
                ViewBag.mensaje = "Ocurrió un error inesperado, por favor intente nuevamente.";
                return View(laActividad);
            }
        }

        [Authorize(Roles = "Administrador")]
        // GET: ActividadFinanciera/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]
        // POST: ActividadFinanciera/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Activar(int id)
        {
            try
            {
      

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadFinanciera/Create.cshtml
@model ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera.ActividadFinancieraDto

@{
    ViewBag.Title = "Registrar Actividad Financiera";
}

<h2>Registrar Actividad Financiera</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.NombreActividadFinanciera, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NombreActividadFinanciera, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NombreActividadFinanciera, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DescripcionActividadFinanciera, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DescripcionActividadFinanciera, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DescripcionActividadFinanciera, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NivelDeRiesgo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.NivelDeRiesgo,
                new List<SelectListItem>
                {
                    new SelectListItem { Text = "Bajo", Value = "1" },
                    new SelectListItem { Text = "Medio", Value = "2" },
                    new SelectListItem { Text = "Alto", Value = "3" }
                },
                htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.NivelDeRiesgo, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.HiddenFor(model => model.Estado)
    </div>


    <br>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>
    </div>
</div>
}
<br>
<div>
    <a href="@Request.UrlReferrer" class="btn btn-secondary btn-md">Volver a la lista</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadFinanciera/Edit.cshtml
@model ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera.ActividadFinancieraDto

@{
    ViewBag.Title = "Editar Actividad Financiera";
}

<h2>Editar Actividad Financiera</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>ActividadFinancieraDto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdActividadFinanciera)

    <div class="form-group">
        @Html.LabelFor(model => model.NombreActividadFinanciera, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NombreActividadFinanciera, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NombreActividadFinanciera, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DescripcionActividadFinanciera, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DescripcionActividadFinanciera, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DescripcionActividadFinanciera, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Estado,
                new List<SelectListItem>
                {
                    new SelectListItem { Text = "Activo", Value = "true" },
                    new SelectListItem { Text = "Inactivo", Value = "false" }
                },
                htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>
    <br>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Editar" class="btn btn-primary" />
        </div>
    </div>
</div>
}
<br>
<div>
    @Html.ActionLink("Volver al listado de actividades", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadFinanciera/Index.cshtml
@model IEnumerable<ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera.ActividadFinancieraDto>

@{
    ViewBag.Title = "Actividades Financieras";
    var mensajeAlerta = TempData["Alerta"] as string;
}
<input type="hidden" id="mensajeAlerta" value="@mensajeAlerta" />
<br />
<h2 class="text-center">Actividades Financieras</h2>
<br />

<p>
    <a href="@Url.Action("Create")" class="btn btn-dark btn-md">Registrar Actividad Financiera</a>
</p>
<div class="table-responsive">
    <table id="myTable" class="table table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.NombreActividadFinanciera)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.DescripcionActividadFinanciera)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.NivelDeRiesgo)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.FechaDeRegistro)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th>Acciones</th>

            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.NombreActividadFinanciera)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.DescripcionActividadFinanciera)
                    </td>
                    @{
                        var nivelRiesgo = "";
                        if (item.NivelDeRiesgo == 1)
                        {
                            nivelRiesgo = "Bajo";
                        }
                        else if (item.NivelDeRiesgo == 2)
                        {

                            nivelRiesgo = "Medio";
                        }

                        else
                        {
                            nivelRiesgo = "Alto";
                        }
                    }
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => nivelRiesgo)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.FechaDeRegistro)
                    </td>
                    @{
                        var estado = "";
                        if (item.Estado == true)
                        {
                            estado = "Activo";
                        }

                        else
                        {
                            estado = "Inactivo";
                        }
                    }
                    <td class="text-center">@estado</td>
                    <td>
                        <div class="d-flex gap-2">
                            <a href="@Url.Action("Edit", "ActividadFinanciera", new { id = item.IdActividadFinanciera })" class="btn btn-primary btn-sm">
                                Editar
                            </a>
                            @if (item.Estado == false)
                            {
                                <a href="@Url.Action("Activar", "ActividadFinanciera", new { id = item.IdActividadFinanciera })" class="btn btn-success btn-sm">
                                    Activar
                                </a>
                            }
                            @if (item.Estado == true)
                            {
                                <a href="@Url.Action("Inactivar", "ActividadFinanciera", new { id = item.IdActividadFinanciera })" class="btn btn-danger btn-sm">
                                    Inactivar
                                </a>
                            }
                        </div>
                    </td>


                </tr>
            }
        </tbody>

    </table>
</div>
@section scripts {
    <script src="~/Scripts/ScriptsFront/ActividadesFinancieras/ListaDataTableActividadesFinancieras.js"></script>
    <script src="~/Scripts/ScriptsFront/Alertas/alerta.js"></script>
}