ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Controllers/ArchivoAnalisisController.cs
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.Detalles;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.Listar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.Registrar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ArchivoAnalisis;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.BitacoraEventos;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.Detalles;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.Listar;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.ObtenerPorId;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.Registrar;
using ControlDeRiesgoFinanciero.LN.BitacoraEventos.Editar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControlDeRiesgoFinanciero.UI.Controllers
{
    public class ArchivoAnalisisController : Controller
    {
        IListarArchivoAnalisisLN _listarArchivoAnalisis;
        IDetallesArchivoAnalisisLN _detallesArchivoAnalisis;
        IRegistrarArchivoAnalisisLN _registrarArchivoAnalisisLN;
        IObtenerArchivoAnalisisPorIdLN _obtenerArchivoAnalisisPorIdLN;
        IRegistrarBitacoraEventosLN _registrarBitacora;

        public ArchivoAnalisisController()
        {
            _listarArchivoAnalisis = new ListarArchivoAnalisisLN();
            _detallesArchivoAnalisis = new DetallesArchivoAnalisisLN();
            _registrarArchivoAnalisisLN = new RegistrarArchivoAnalisisLN();
            _obtenerArchivoAnalisisPorIdLN = new ObtenerArchivoAnalisisPorIdLN();
            _registrarBitacora = new RegistrarBitacoraEventosLN();
        }

        [Authorize(Roles = "Administrador, Analista")]

        // GET: ArchivoAnalisis
        public ActionResult Listar()
        {
            ViewBag.Title = "Los Archivos de Análisis";
            List<ArchivoAnalisisDto> laListaDeArchivos = _listarArchivoAnalisis.Listar();
            return View(laListaDeArchivos);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Details/5
        public ActionResult Detalles(int id)
        {
            ViewBag.Title = "Detalles del Archivo";
            ArchivoAnalisisDto archivo = _obtenerArchivoAnalisisPorIdLN.Obtener(id);
            if (archivo == null)
            {
                return HttpNotFound();
            }
            return View(archivo);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: ArchivoAnalisis/Create
        [HttpPost]
        public async Task<ActionResult> Create(ArchivoAnalisisDto modeloDelArchivo)
        {
            try
            {
                int cantidadDeDatosGuardados = await _registrarArchivoAnalisisLN.Registrar(modeloDelArchivo);
              
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "ARCHIVO_ANALISIS",
                    TipoDeEvento = "Registrar",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Se registro un nuevo archivo de analisis",
                    DatosAnteriores = "Vacio",
                    DatosPosteriores = $"Nombre: {modeloDelArchivo.Nombre}",
                    StackTrace = ""
                });
             
                TempData["Alerta"] = "El archivo de analisis se registro con exito.";
                TempData.Keep("Alerta"); // Mantener TempData para la próxima solicitud

                return RedirectToAction("Listar");
            }
            catch(Exception ex)
            {
             
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "ARCHIVO_ANALISIS",
                    TipoDeEvento = "Error",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Error al registrar un nuevo archivo",
                    DatosAnteriores = "",
                    DatosPosteriores = "",
                    StackTrace = ex.StackTrace
                });
                TempData["Alerta"] = $"Error al crear el registro: {ex.Message}";
                TempData.Keep("Alerta");
                return View();
            }
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: ArchivoAnalisis/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: ArchivoAnalisis/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Controllers/PalabrasClaveController.cs
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.PalabrasClave.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.PalabrasClave.Listar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.PalabrasClave.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.PalabrasClave.Registrar;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.BitacoraEventos;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.PalabrasClave;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.Personas;
using ControlDeRiesgoFinanciero.LN.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.LN.PalabrasClave.Editar;
using ControlDeRiesgoFinanciero.LN.PalabrasClave.Listar;
using ControlDeRiesgoFinanciero.LN.PalabrasClave.ObtenerPorId;
using ControlDeRiesgoFinanciero.LN.PalabrasClave.Registrar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControlDeRiesgoFinanciero.UI.Controllers
{
    public class PalabrasClaveController : Controller
    {
        IListarPalabraClaveLN _listarPalabraClave;
        IRegistrarPalabraClaveLN _registrarPalabraClave;
        IEditarPalabraClaveLN _editarPalabraClave;
        IObtenerPalabraClavePorIdLN _obtenerPalabraClave;
        IRegistrarBitacoraEventosLN _registrarBitacora;


        public PalabrasClaveController()
        {
            _listarPalabraClave = new ListarPalabraClaveLN();
            _registrarPalabraClave = new RegistrarPalabraClaveLN();
            _editarPalabraClave = new EditarPalabraClaveLN();
            _obtenerPalabraClave = new ObtenerPalabraClavePorIdLN();
            _registrarBitacora = new RegistrarBitacoraEventosLN();

        }

        [Authorize(Roles = "Administrador, Analista")]


        // GET: PalabrasClave
        public ActionResult ListarPalabraClave()
        {
            List<PalabrasClaveDto> laListaDePalabras = _listarPalabraClave.Listar();
            return View(laListaDePalabras);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: PalabrasClave/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: PalabrasClave/Create
        public ActionResult RegistrarPalabraClave()
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: PalabrasClave/Create
        [HttpPost]
        public async Task<ActionResult> RegistrarPalabraClave(PalabrasClaveDto modeloDeLaPalabra)
        {
            try
            {
               
                var palabraExistente = _listarPalabraClave.Listar()
                    .FirstOrDefault(laPalabra => laPalabra.Palabra == modeloDeLaPalabra.Palabra);

                if (palabraExistente != null)
                {
                   
                    ViewBag.MensajeDeError = "La palabra ingresada ya está registrada.";
                    return View(modeloDeLaPalabra);
                }

               
                int cantidadDeDatosGuardados = await _registrarPalabraClave.Guardar(modeloDeLaPalabra);
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "PALABRAS_CLAVE",
                    TipoDeEvento = "Registrar",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Se registro uan palabra clave",
                    DatosAnteriores = "Vacio",
                    DatosPosteriores = $"Palabra: {modeloDeLaPalabra.Palabra}",
                    StackTrace = ""
                });
              
                TempData["Alerta"] = "La palabra clave se registro con exito.";
                TempData.Keep("Alerta"); // Mantener TempData para la próxima solicitud

                return RedirectToAction("ListarPalabraClave");
            }
            catch(Exception ex)
            {
              
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "PALABRAS_CLAVE",
                    TipoDeEvento = "Error",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Error al registrar la palabra clave",
                    DatosAnteriores = "",
                    DatosPosteriores = "",
                    StackTrace = ex.StackTrace
                });
            
                TempData["Alerta"] = $"Error al crear el registro: {ex.Message}";
                TempData.Keep("Alerta");
                return View();
            }
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: PalabrasClave/Edit/5
        public ActionResult EditarPalabraClave(int id)
        {
            PalabrasClaveDto laPalabra = _obtenerPalabraClave.Obtener(id);
            return View(laPalabra);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: PalabrasClave/Edit/5
        [HttpPost]
        public async Task<ActionResult> EditarPalabraClave(PalabrasClaveDto laPalabra)
        {
            try
            {
                var existePalabra = _listarPalabraClave.Listar();
                bool palabraDuplicada = existePalabra
                    .Any(laPalabraValida => laPalabraValida.Palabra == laPalabra.Palabra && laPalabraValida.IdPalabra != laPalabra.IdPalabra);

                if (palabraDuplicada)
                {
                    ModelState.AddModelError("Palabra", "Ya existe esa palabra clave.");
                    return View(laPalabra);
                }
                else
                {
                    var palabraAnterior = _listarPalabraClave.Listar().FirstOrDefault(a => a.IdPalabra == laPalabra.IdPalabra);

                  
                    await _registrarBitacora.Registrar(new BitacoraEventosDto
                    {
                        TablaDeEvento = "PALABRAS_CLAVE",
                        TipoDeEvento = "Editar",
                        FechaDeEvento = DateTime.Now,
                        DescripcionDeEvento = $"Se actualizó correctamente",
                        DatosAnteriores = $"Palabra: {palabraAnterior.Palabra}\n" +
                        $"Orden: {palabraAnterior.Orden}",
                        DatosPosteriores = $"Palabra: {laPalabra.Palabra}\n" +
                        $"Orden: {laPalabra.Orden}",
                        StackTrace = "" 
                    });

                    int cantidadDeDatosActualizados = await _editarPalabraClave.Editar(laPalabra);

                    return RedirectToAction("ListarPalabraClave");
                }
            }
            catch(Exception ex)
            {
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "PALABRAS_CLAVE",
                    TipoDeEvento = "Error",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Error al editar",
                    DatosAnteriores = "", 
                    DatosPosteriores = "", 
                    StackTrace = ex.StackTrace 
                });
                ViewBag.cantidadDeDatosActualizados = 0;
                ViewBag.mensaje = "Ocurrió un error inesperado, por favor intente nuevamente.";
                return View(laPalabra);
            }
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: PalabrasClave/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: PalabrasClave/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/ComponentesExternos/DataTable/dataTables.dataTables.min.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
        <div class="container-fluid">
          
            <a class="navbar-brand fw-bold" href="@Url.Action("Index", "Home")">
                <i class="bi bi-house-door-fill me-2"></i>Sistema de Gestión Financiera
            </a>

          
            <div class="d-flex justify-content-center w-100">
                <ul class="navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Personas", "ListarPersonas", "Personas",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Actividades Financieras", "Index", "ActividadFinanciera",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Bitácora de Eventos", "Index", "BitacoraEventos",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Archivos de Análisis", "Listar", "ArchivoAnalisis",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Análisis de Personas", "Listar", "AnalizarPersona",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Palabras Clave", "ListarPalabraClave", "PalabrasClave",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                        }
                        if (User.IsInRole("Analista"))
                        {
                            <li class="nav-item">
                                @Html.ActionLink("Personas", "ListarPersonas", "Personas",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Archivos de Análisis", "Listar", "ArchivoAnalisis",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Análisis de Personas", "Listar", "AnalizarPersona",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Palabras Clave", "ListarPalabraClave", "PalabrasClave",
                                                  new { area = "" }, new { @class = "nav-link" })
                            </li>
                        }
                    }
                </ul>
            </div>

      
            <div class="d-flex justify-content-end">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    @*/ @Scripts.Render("~/bundles/jquery") /*@
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/ComponentesExternos/DataTable/dataTables.min.js"></script>
    <script src="~/Scripts/ComponentesExternos/SweetAlert/sweetalert2@11.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>