ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Controllers/ActividadPersonaController.cs
using ControlDeRiesgoFinanciero.Abstracciones.AccesoADatos.Interfaces.ActividadPersona.ListarActividadesNoRegistradas;
using ControlDeRiesgoFinanciero.Abstracciones.AccesoADatos.Interfaces.ActividadPersona.ListarPersonas;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadFinanciera.Listar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.Actualizar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.Eliminar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.Listar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.ListarActividadesNoRegistradas;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.ListarPersonas;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ActividadPersona.Registrar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.Personas.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadPersona;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.BitacoraEventos;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.Personas;
using ControlDeRiesgoFinanciero.LN.ActividadFinanciera.Listar;
using ControlDeRiesgoFinanciero.LN.ActividadPersona.Actualizar;
using ControlDeRiesgoFinanciero.LN.ActividadPersona.Eliminar;
using ControlDeRiesgoFinanciero.LN.ActividadPersona.Listar;
using ControlDeRiesgoFinanciero.LN.ActividadPersona.ListarActividadesNoRegistradas;
using ControlDeRiesgoFinanciero.LN.ActividadPersona.ListarPersonaPorId;
using ControlDeRiesgoFinanciero.LN.ActividadPersona.ObtenerPorId;
using ControlDeRiesgoFinanciero.LN.ActividadPersona.Registrar;
using ControlDeRiesgoFinanciero.LN.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.LN.Personas.ObtenerPorId;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControlDeRiesgoFinanciero.UI.Controllers
{
    public class ActividadPersonaController : Controller
    {

        IRegistrarActividadPersonaLN _registrar;
        IEliminarActividadPersonaLN _eliminar;
        IListarActividadPersonaLN _listar;
        IObtenerActividadPersonaPorIdLN _obtenerPorId;
        IListarPersonasPorIdLN _obtenerPersonas;
        IListarActividadesNoRegistradasLN _listarNoRgistradas;
        IListarActividadFinancieraLN _listarActividadFinanciera;
        IObtenerPersonasPorIdLN _obtenerPersonaPorId;
        IActualizarActividadPersonaLN _actualizar;
        IRegistrarBitacoraEventosLN _registrarBitacora;
        public ActividadPersonaController()
        {
            _listarActividadFinanciera = new ListarActividadFinancieraLN();
            _registrar = new RegistrarActividadPersonaLN();
            _eliminar = new EliminarActividadPersonaLN();
            _listar = new ListarActividadPersonaLN();
            _obtenerPorId = new ObtenerActividadPersonaPorIdLN();
            _obtenerPersonas = new ListarPersonaPorIdLN();
            _listarNoRgistradas = new ListarActividadesNoRegistradasLN();
            _obtenerPersonaPorId = new ObtenerPersonasPorIdLN();
            _actualizar = new ActualizarActividadPersonaLN();
            _registrarBitacora = new RegistrarBitacoraEventosLN();
        }

        [Authorize(Roles = "Administrador, Analista")]

        // GET: ActividadPersona
        public ActionResult Index()
        {
            ViewBag.Title = "Actividades Personas";
            List<ActividadPersonaDto> laListaDeActividades = _listar.Listar();
            return View(laListaDeActividades);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ActividadPersona/Detalles/5
        public async Task<ActionResult> Actividades(int idPersona)
        {
            try
            {
               
                ViewBag.IdPersona = idPersona;

                List<ActividadPersonaDto> actividades = _obtenerPersonas.ListarActividades(idPersona);
                return View(actividades);
            }
            catch
            {
                return View();
            }
        }




        [Authorize(Roles = "Administrador, Analista")]
        // GET: ActividadPersona/Create
        public ActionResult Create(int idPersona)
        {
           
            var modeloDeActividadPersona = new ActividadPersonaDto
            {
                IdPersona = idPersona
            };

            ViewBag.Title = "Actividades Personas";

           
            List<ActividadFinancieraDto> todasLasActividades = _listarActividadFinanciera.Listar()
                .Where(a => a.Estado)
                .ToList();

            List<ActividadPersonaDto> actividadesRegistradas = _listarNoRgistradas.ListarPersonasNoRegistradas(idPersona);

           
            var actividadesNoRegistradas = todasLasActividades
                .Where(actividad =>
                    !actividadesRegistradas.Any(registrada => registrada.IdActividadFinanciera == actividad.IdActividadFinanciera))
                .ToList();

       
            ViewBag.ActividadesDisponibles = actividadesNoRegistradas
                .Select(a => new SelectListItem
                {
                    Value = a.IdActividadFinanciera.ToString(),
                    Text = a.NombreActividadFinanciera 
                })
                .ToList();

            return View(modeloDeActividadPersona);
        }



        [Authorize(Roles = "Administrador, Analista")]
        [HttpPost]
        public async Task<ActionResult> Create(ActividadPersonaDto modelo)
        {
            try
            {
               
                var actividadExistente = _listar.Listar()
                    .FirstOrDefault(a =>
                        a.IdPersona == modelo.IdPersona &&
                        a.IdActividadFinanciera == modelo.IdActividadFinanciera);

                if (actividadExistente != null)
                {
                    if (!actividadExistente.Estado)
                    {
                    
                        actividadExistente.Estado = true;
                        int datosActualizados = await _actualizar.Actualizar(actividadExistente);

                        if (datosActualizados > 0)
                        {
                            var actividadFinanciera = _listarActividadFinanciera.Listar()
                                .FirstOrDefault(a => a.IdActividadFinanciera == modelo.IdActividadFinanciera);

                            string nombreActividad = actividadFinanciera?.NombreActividadFinanciera ?? "Desconocido";

                        
                            await _registrarBitacora.Registrar(new BitacoraEventosDto
                            {
                                TablaDeEvento = "ACTIVIDAD_PERSONA",
                                TipoDeEvento = "Reactivar",
                                FechaDeEvento = DateTime.Now,
                                DescripcionDeEvento = "Se reactivó la actividad financiera",
                                DatosAnteriores = "Estado: Inactivo",
                                DatosPosteriores = $"Estado: Activo, Nombre: {nombreActividad}",
                                StackTrace = ""
                            });

                            TempData["Alerta"] = "La actividad se activó correctamente.";
                            TempData.Keep("Alerta");
                            return RedirectToAction("Actividades", new { idPersona = modelo.IdPersona });
                        }
                        else
                        {
                            TempData["Alerta"] = "Error al reactivar la actividad. Intente nuevamente.";
                            TempData.Keep("Alerta");
                            return View(modelo);
                        }
                    }

                    TempData["Alerta"] = "La actividad ya está activa.";
                    TempData.Keep("Alerta");
                    return RedirectToAction("Actividades", new { idPersona = modelo.IdPersona });
                }

             
                modelo.Estado = true;
                int datosGuardados = await _registrar.Registrar(modelo);

                if (datosGuardados > 0)
                {
                    var actividadFinanciera = _listarActividadFinanciera.Listar()
                        .FirstOrDefault(a => a.IdActividadFinanciera == modelo.IdActividadFinanciera);

                    string nombreActividad = actividadFinanciera?.NombreActividadFinanciera ?? "Desconocido";

             
                    await _registrarBitacora.Registrar(new BitacoraEventosDto
                    {
                        TablaDeEvento = "ACTIVIDAD_PERSONA",
                        TipoDeEvento = "Registrar",
                        FechaDeEvento = DateTime.Now,
                        DescripcionDeEvento = "Se registró una nueva actividad financiera",
                        DatosAnteriores = "Vacío",
                        DatosPosteriores = $"Nombre de la actividad financiera creada: {nombreActividad}",
                        StackTrace = ""
                    });

                    TempData["Alerta"] = "La actividad se registró correctamente.";
                    TempData.Keep("Alerta");
                    return RedirectToAction("Actividades", new { idPersona = modelo.IdPersona });
                }
                else
                {
                    TempData["Alerta"] = "Error al registrar la actividad.";
                    TempData.Keep("Alerta");
                    return View(modelo);
                }
            }
            catch (Exception ex)
            {

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadPersona/Actividades.cshtml
@model IEnumerable<ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadPersona.ActividadPersonaDto>
@{

    var mensajeAlerta = TempData["Alerta"] as string;
}

<input type="hidden" id="mensajeAlerta" value="@mensajeAlerta" />
<br />
<h2 class="text-center">Listar Personas</h2>
<br />

<p>
    <a href="@Url.Action("Create", new { idPersona = ViewBag.IdPersona })" class="btn btn-dark">Crear nueva actividad financiera</a>

</p>
<br />
<div class="table-responsive">
    <table id="myTable" class="table table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th>Nombre de la Actividad</th>
                <th>Nivel de Riesgo</th>
                <th>Fecha de Registro</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var actividad in Model)
            {
                <tr>
                    <td>@actividad.NombreActividadFinanciera</td>
                    <td>
                        @if (actividad.NivelDeRiesgo == 1)
                        {
                            @:Bajo
                        }
                        else if (actividad.NivelDeRiesgo == 2)
                        {
                            @:Medio
                        }
                        else
                        {
                            @:Alto
                        }
                    </td>
                    <td>@actividad.FechaDeRegistro</td>
                    <td>

                        <a href="@Url.Action("Edit", "ActividadPersona", new { id = actividad.IdActividadPersona })" class="btn btn-danger btn-sm">
                            Eliminar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
    @section scripts {
        <script src="~/Scripts/ScriptsFront/ArchivoAnalisis/ListaDataTableArchivoAnalisis.js"></script>

        <script src="~/Scripts/ScriptsFront/Alertas/alerta.js"></script>
    }

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadPersona/Create.cshtml
@model ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadPersona.ActividadPersonaDto

@{
    ViewBag.Title = "Create";
}

<h2>Crear actividad financiera</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.IdActividadPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdActividadPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdActividadPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.IdPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersona, "", new { @class = "text-danger" })
            </div>
        </div>







        <div class="form-group">
            @Html.LabelFor(model => model.IdActividadFinanciera, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(
    model => model.IdActividadFinanciera,
    ViewBag.ActividadesDisponibles as IEnumerable<SelectListItem>,
    new { @class = "form-control" }
     )
                @Html.ValidationMessageFor(model => model.IdActividadFinanciera, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Estado, new { @Value = "true" })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </div>

    </div>
    <br />
}

<div>
    <a href="@Request.UrlReferrer" class="btn btn-secondary btn-md">Volver a la lista</a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadPersona/Delete.cshtml
@model ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadPersona.ActividadPersonaDto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ActividadPersonaDto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdActividadPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdActividadPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdActividadFinanciera)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdActividadFinanciera)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdPersona)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadPersona/Edit.cshtml
@model ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadPersona.ActividadPersonaDto

@{
    ViewBag.Title = "Edit";
}
<br />
<h2 class="text-center">Eliminar Actividad</h2>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.IdActividadPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdActividadPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdActividadPersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.IdActividadFinanciera, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdActividadFinanciera, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdActividadFinanciera, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display: none;">
            @Html.LabelFor(model => model.IdPersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdPersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdPersona, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group d-flex justify-content-center align-items-center" style="height: 100px;">
            <div class="col-md-10">
                <p class="text-center" style="font-size: 16px; color: #f44336; font-weight: bold; margin: 0;">
                    Está a punto de desactivar este registro. Esta acción no puede ser revertida.
                </p>
            </div>
        </div>



        <div class="form-group text-center">
            <div class="col-md-12">
                <input type="submit" value="Eliminar" class="btn btn-danger btn-lg" style="padding: 10px 20px;" />
            </div>
        </div>

    </div>
    <br />
}

<div >
    <a href="@Request.UrlReferrer" class="btn btn-secondary btn-md">Volver a la lista</a>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/ActividadPersona/Index.cshtml
@model IEnumerable<ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadPersona.ActividadPersonaDto>

@{
    ViewBag.Title = "Index";
    var mensajeAlerta = TempData["Alerta"] as string;
}
<input type="hidden" id="mensajeAlerta" value="@mensajeAlerta" />
<br />
<h2 class="text-center">Listar Personas</h2>
<br />
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.NombreActividadFinanciera)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NivelDeRiesgo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaDeRegistro)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreActividadFinanciera)
            </td>
            <td>
                @{
                    var nivelRiesgo = "";
                    if (item.NivelDeRiesgo == 1)
                    {
                        nivelRiesgo = "Bajo";
                    }
                    else if (item.NivelDeRiesgo == 2)
                    {
                        nivelRiesgo = "Medio";
                    }
                    else if (item.NivelDeRiesgo == 3)
                    {
                        nivelRiesgo = "Alto";
                    }

                }
                @nivelRiesgo
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDeRegistro)
            </td>
            <td>
                @Html.ActionLink("Delete", "Edit", new { id = item.IdActividadPersona }) |

            </td>
        </tr>

    }

</table>
}
@section scripts {
    <script src="~/Scripts/ScriptsFront/Personas/ListaDataTablePersonas.js"></script>
    <script src="~/Scripts/ScriptsFront/Alertas/alerta.js"></script>
}