ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Controllers/ArchivoAnalisisController.cs
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.Detalles;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.Listar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.ArchivoAnalisis.Registrar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ActividadFinanciera;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.ArchivoAnalisis;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.BitacoraEventos;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.Detalles;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.Listar;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.ObtenerPorId;
using ControlDeRiesgoFinanciero.LN.ArchivoAnalisis.Registrar;
using ControlDeRiesgoFinanciero.LN.BitacoraEventos.Editar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControlDeRiesgoFinanciero.UI.Controllers
{
    public class ArchivoAnalisisController : Controller
    {
        IListarArchivoAnalisisLN _listarArchivoAnalisis;
        IDetallesArchivoAnalisisLN _detallesArchivoAnalisis;
        IRegistrarArchivoAnalisisLN _registrarArchivoAnalisisLN;
        IObtenerArchivoAnalisisPorIdLN _obtenerArchivoAnalisisPorIdLN;
        IRegistrarBitacoraEventosLN _registrarBitacora;

        public ArchivoAnalisisController()
        {
            _listarArchivoAnalisis = new ListarArchivoAnalisisLN();
            _detallesArchivoAnalisis = new DetallesArchivoAnalisisLN();
            _registrarArchivoAnalisisLN = new RegistrarArchivoAnalisisLN();
            _obtenerArchivoAnalisisPorIdLN = new ObtenerArchivoAnalisisPorIdLN();
            _registrarBitacora = new RegistrarBitacoraEventosLN();
        }

        [Authorize(Roles = "Administrador, Analista")]

        // GET: ArchivoAnalisis
        public ActionResult Listar()
        {
            ViewBag.Title = "Los Archivos de Análisis";
            List<ArchivoAnalisisDto> laListaDeArchivos = _listarArchivoAnalisis.Listar();
            return View(laListaDeArchivos);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Details/5
        public ActionResult Detalles(int id)
        {
            ViewBag.Title = "Detalles del Archivo";
            ArchivoAnalisisDto archivo = _obtenerArchivoAnalisisPorIdLN.Obtener(id);
            if (archivo == null)
            {
                return HttpNotFound();
            }
            return View(archivo);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: ArchivoAnalisis/Create
        [HttpPost]
        public async Task<ActionResult> Create(ArchivoAnalisisDto modeloDelArchivo)
        {
            try
            {
                int cantidadDeDatosGuardados = await _registrarArchivoAnalisisLN.Registrar(modeloDelArchivo);
              
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "ARCHIVO_ANALISIS",
                    TipoDeEvento = "Registrar",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Se registro un nuevo archivo de analisis",
                    DatosAnteriores = "Vacio",
                    DatosPosteriores = $"Nombre: {modeloDelArchivo.Nombre}",
                    StackTrace = ""
                });
             
                TempData["Alerta"] = "El archivo de analisis se registro con exito.";
                TempData.Keep("Alerta"); // Mantener TempData para la próxima solicitud

                return RedirectToAction("Listar");
            }
            catch(Exception ex)
            {
             
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "ARCHIVO_ANALISIS",
                    TipoDeEvento = "Error",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Error al registrar un nuevo archivo",
                    DatosAnteriores = "",
                    DatosPosteriores = "",
                    StackTrace = ex.StackTrace
                });
                TempData["Alerta"] = $"Error al crear el registro: {ex.Message}";
                TempData.Keep("Alerta");
                return View();
            }
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: ArchivoAnalisis/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: ArchivoAnalisis/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: ArchivoAnalisis/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlDeRiesgoFinanciero.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Controllers/PersonasController.cs
using ControlDeRiesgoFinanciero.Abstracciones.AccesoADatos.Interfaces.Personas.CambiarEstado;
using ControlDeRiesgoFinanciero.Abstracciones.AccesoADatos.Interfaces.Personas.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.General;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.Personas.CambiarEstado;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.Personas.Editar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.Personas.Listar;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.Personas.ObtenerPorId;
using ControlDeRiesgoFinanciero.Abstracciones.LN.Interfaces.Personas.Registrar;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.BitacoraEventos;
using ControlDeRiesgoFinanciero.Abstracciones.Modelos.Personas;
using ControlDeRiesgoFinanciero.LN.BitacoraEventos.Editar;
using ControlDeRiesgoFinanciero.LN.General;
using ControlDeRiesgoFinanciero.LN.Personas.CambiarEstado;
using ControlDeRiesgoFinanciero.LN.Personas.Editar;
using ControlDeRiesgoFinanciero.LN.Personas.Listar;
using ControlDeRiesgoFinanciero.LN.Personas.ObtenerPorId;
using ControlDeRiesgoFinanciero.LN.Personas.Registrar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ControlDeRiesgoFinanciero.UI.Controllers
{
    public class PersonasController : Controller
    {
        IListarPersonasLN _listarPersonas;
        IRegistrarPersonasLN _registrarPersonas;
        IObtenerPersonasPorIdLN _obtenerPersonaPorId;
        IEditarPersonasLN _editarPersonas;
        ICambiarEstadoPersonasLN _cambiarEstado;
        IFecha _fecha;
        IRegistrarBitacoraEventosLN _registrarBitacora;

        public PersonasController()
        {
            _listarPersonas = new ListarPersonasLN();
            _registrarPersonas = new RegistrarPersonasLN();
            _obtenerPersonaPorId = new ObtenerPersonasPorIdLN();
            _editarPersonas = new EditarPersonasLN();
            _fecha = new Fecha();
            _cambiarEstado = new CambiarEstadoPersonasLN(_fecha);
            _registrarBitacora = new RegistrarBitacoraEventosLN();
        }

        [Authorize(Roles = "Administrador, Analista")]

        // GET: Personas
        public ActionResult ListarPersonas()
        {
            List<PersonasDto> laListaDePersonas = _listarPersonas.Listar();
            return View(laListaDePersonas);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: Personas/Details/5
        public ActionResult DetallesPersona(int id)
        {
            PersonasDto persona = _obtenerPersonaPorId.Obtener(id);
            return View(persona);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: Personas/Create
        public ActionResult RegistrarPersonas()
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: Personas/Create
        [HttpPost]
        public async Task<ActionResult> RegistrarPersonas(PersonasDto modeloDeLaPersona)
        {
            try
            {
                var personaExistente = _listarPersonas.Listar()
                    .FirstOrDefault(laIdentificacion => laIdentificacion.IdentificacionPersona == modeloDeLaPersona.IdentificacionPersona);

                if (personaExistente != null)
                {
                    ViewBag.MensajeDeError = "La identificación ingresada ya está registrada.";
                    return View(modeloDeLaPersona);
                }

             
                int cantidadDeDatosGuardados = await _registrarPersonas.Guardar(modeloDeLaPersona);
              
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "PERSONAS_TABLA",
                    TipoDeEvento = "Registrar",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Se registro una nueva persona",
                    DatosAnteriores = "Vacio",
                    DatosPosteriores = $"Nombre: {modeloDeLaPersona.NombrePersona}",
                    StackTrace = ""
                });
                TempData["Alerta"] = " ";
                return RedirectToAction("ListarPersonas");
            }
            catch(Exception ex)
            {
                
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "PERSONAS_TABLA",
                    TipoDeEvento = "Error",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = "Error al registrar una nueva persona",
                    DatosAnteriores = "",
                    DatosPosteriores = "",
                    StackTrace = ex.StackTrace
                });
                TempData["Alerta"] = "Error al crear el registro: ";
                return View();
            }
        }

        [Authorize(Roles = "Administrador, Analista")]
        // GET: Personas/Edit/5
        public ActionResult EditarPersonas(int id)
        {
            PersonasDto elNombre = _obtenerPersonaPorId.Obtener(id);
            return View(elNombre);
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: Personas/Edit/5
        [HttpPost]
        public async Task<ActionResult> EditarPersonas(PersonasDto laPersona)
        {
            try
            {
              
                var personaAnterior = _listarPersonas.Listar()
                    .FirstOrDefault(a => a.IdPersona == laPersona.IdPersona);

                if (personaAnterior == null)
                {
                    ViewBag.mensaje = "La persona no fue encontrada en la base de datos.";
                    return View(laPersona);
                }

             
                int cantidadDeDatosEditados = await _editarPersonas.Editar(laPersona);

                if (cantidadDeDatosEditados > 0)
                {

                    await _registrarBitacora.Registrar(new BitacoraEventosDto
                    {
                        TablaDeEvento = "PERSONAS_TABLA",
                        TipoDeEvento = "Editar",
                        FechaDeEvento = DateTime.Now,
                        DescripcionDeEvento = "Se realizó una edición en los datos de una persona.",
                        DatosAnteriores = $"Nombre: {personaAnterior.NombrePersona}\n" +
                      $"Primer Apellido: {personaAnterior.PrimerApellidoPersona}\n" +
                      $"Segundo Apellido: {personaAnterior.SegundoApellidoPersona}\n" +
                      $"Teléfono: {personaAnterior.Telefono}\n" +
                      $"Correo: {personaAnterior.CorreoElectronico}\n" +
                      $"Dirección: {personaAnterior.Direccion}\n" +
                      $"Estado: {personaAnterior.Estado}",
                       DatosPosteriores = $"Nombre: {laPersona.NombrePersona}\n" +
                       $"Primer Apellido: {laPersona.PrimerApellidoPersona}\n" +
                       $"Segundo Apellido: {laPersona.SegundoApellidoPersona}\n" +
                       $"Teléfono: {laPersona.Telefono}\n" +
                       $"Correo: {laPersona.CorreoElectronico}\n" +
                       $"Dirección: {laPersona.Direccion}\n" +
                       $"Estado: {laPersona.Estado}",
                        StackTrace = string.Empty
                    });


                    return RedirectToAction("ListarPersonas");
                }

              
                ViewBag.mensaje = "No se realizaron cambios en los datos.";
                return View(laPersona);
            }
            catch (Exception ex)
            {
                await _registrarBitacora.Registrar(new BitacoraEventosDto
                {
                    TablaDeEvento = "PERSONAS_TABLA",
                    TipoDeEvento = "ERROR",
                    FechaDeEvento = DateTime.Now,
                    DescripcionDeEvento = $"Error al editar la persona",
                    DatosAnteriores = "",
                    DatosPosteriores = "",
                    StackTrace = ex.StackTrace
                });

                ViewBag.mensaje = "Ocurrió un error inesperado, por favor, intente nuevamente.";
                ViewBag.error = ex.Message;
                return View(laPersona);
            }
        }


        [Authorize(Roles = "Administrador, Analista")]
        // GET: Personas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        [Authorize(Roles = "Administrador, Analista")]
        // POST: Personas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public async Task<ActionResult> Activar(int id)
        {
            try
            {
                bool resultado = await _cambiarEstado.CambiarEstado(id, true);

                if (resultado)
                {
                    await _registrarBitacora.Registrar(new BitacoraEventosDto
                    {
                        TablaDeEvento = "PERSONAS_TABLA",
                        TipoDeEvento = "Activar",
                        FechaDeEvento = DateTime.Now,
                        DescripcionDeEvento = $"Se reactivó la persona",
                        DatosAnteriores = $"Estado: Inactivo",
                        DatosPosteriores = $"Estado: Activo",
                        StackTrace = ""
                    });
                    return RedirectToAction("ListarPersonas");
                }
                else
                {

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

ControlDeRiesgoFinanciero/ControlDeRiesgoFinanciero.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<main>
    <section class="text-center py-5" style="background-color: #25282B; color: white;">
        <div class="container">
            <h1 class="display-4 fw-bold">Bienvenido al Sistema de Gestión Financiera</h1>
            <p class="lead mt-3">
                Administra actividades financieras, analiza posibles riesgos, y contribuye a la prevención de lavado de activos y financiamiento del terrorismo.
            </p>
            <a href="#modulos" class="btn btn-light btn-lg mt-4">Explorar Módulos &raquo;</a>
        </div>
    </section>


    <section id="acerca" class="py-5">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <img src="https://www.ceupe.com/images/easyblog_articles/2361/b2ap3_amp_funciones-de-gestin-financiera.jpg" alt="Gestión Financiera" class="img-fluid rounded shadow">
                </div>
                <div class="col-lg-6">
                    <h2 class="fw-bold">Acerca del Sistema</h2>
                    <p class="text-muted">
                        Este sistema está diseñado para fortalecer los esfuerzos en la prevención de lavado de activos y financiamiento del terrorismo (LAFT).
                        Permite analizar datos relevantes, gestionar actividades y detectar posibles riesgos en operaciones financieras.
                    </p>
                    <ul class="list-unstyled">
                        <li><i class="bi bi-check-circle-fill text-success me-2"></i> Gestión de personas vinculadas a actividades financieras</li>
                        <li><i class="bi bi-check-circle-fill text-success me-2"></i> Análisis de noticias y documentos relacionados con riesgos</li>
                        <li><i class="bi bi-check-circle-fill text-success me-2"></i> Prevención de actividades sospechosas según normativa</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="modulos" class="py-5 bg-light">
        <div class="container text-center">
            <h2 class="fw-bold mb-5">Módulos Principales</h2>
            <div class="row g-4">
                <div class="col-md-6 col-lg-3">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <i class="bi bi-people-fill text-primary display-4"></i>
                            <h5 class="card-title mt-3">Gestión de Personas</h5>
                            <p class="card-text text-muted">
                                Gestiona clientes asociados a actividades financieras y valida antecedentes según la normativa.
                            </p>
                            <a href="@Url.Action("ListarPersonas", "Personas")" class="btn btn-outline-primary">Ir al módulo</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <i class="bi bi-journal-text text-primary display-4"></i>
                            <h5 class="card-title mt-3">Actividades Financieras</h5>
                            <p class="card-text text-muted">
                                Registra y supervisa actividades financieras, asegurando el cumplimiento de normativas LAFT.
                            </p>
                            <a href="@Url.Action("Index", "ActividadFinanciera")" class="btn btn-outline-primary">Ir al módulo</a>
                        </div>
                    </div>
                </div>
               
                <div class="col-md-6 col-lg-3">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <i class="bi bi-folder-fill text-primary display-4"></i>
                            <h5 class="card-title mt-3">Archivos de Análisis</h5>
                            <p class="card-text text-muted">
                                Administra y analiza documentos clave relacionados con posibles casos de riesgo.
                            </p>
                            <a href="@Url.Action("Listar", "ArchivoAnalisis")" class="btn btn-outline-primary">Ir al módulo</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <i class="bi bi-folder-fill text-primary display-4"></i>
                            <h5 class="card-title mt-3">Palabras Clave</h5>
                            <p class="card-text text-muted">
                                Define palabras clave críticas para identificar riesgos en documentos y análisis.
                            </p>
                            <a href="@Url.Action("ListarPalabraClave", "PalabrasClave")" class="btn btn-outline-primary">Ir al módulo</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="py-5 bg-dark text-white">
        <div class="container text-center">
            <h3 class="fw-bold">Fortalece la prevención de riesgos financieros</h3>
            <p class="mt-3">Utiliza herramientas avanzadas para cumplir con las normativas LAFT y proteger tu organización.</p>
         
        </div>
    </section>
</main>